language: python

python:
  - 3.7
  - 3.8

install:
  - pip install -r requirements.txt

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - python -m unittest

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# notifications:
#   slack:
#     secure: your_token_key
